CREATE TABLE "active_admin_comments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "namespace" varchar(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "resource_id" varchar(255) NOT NULL,
  "resource_type" varchar(255) NOT NULL,
  "author_id" integer DEFAULT NULL,
  "author_type" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "assignment" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "scrambled" boolean DEFAULT false,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "description" text DEFAULT NULL,
  "points_multiplier" integer DEFAULT NULL,
  "user_id" integer DEFAULT NULL,
  "external_id" varchar(255) DEFAULT NULL,
  "is_public" boolean DEFAULT NULL,
  "submission_policy_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "assignment_offering" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "course_offering_id" integer NOT NULL,
  "assignment_id" integer NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "available_from" timestamp DEFAULT NULL,
  "due_at" timestamp DEFAULT NULL,
  "accept_until" timestamp DEFAULT NULL,
  "published" boolean NOT NULL DEFAULT true,
  "time_limit" integer DEFAULT NULL,
  "workout_policy_id" integer DEFAULT NULL,
  "continue_from_workout_id" integer DEFAULT NULL,
  "lms_assignment_id" varchar(255) DEFAULT NULL,
  "most_recent" boolean DEFAULT true,
  "lms_assignment_url" varchar(255) DEFAULT NULL,
  "lis_outcome_service_url" varchar(255) DEFAULT NULL,
  "attempt_limit" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "attempts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "exercise_version_id" integer NOT NULL,
  "submit_time" timestamp NOT NULL,
  "submit_num" integer NOT NULL,
  "score" double precision DEFAULT 0,
  "experience_earned" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "workout_score_id" integer DEFAULT NULL,
  "active_score_id" integer DEFAULT NULL,
  "feedback_ready" boolean DEFAULT NULL,
  "time_taken" numeric(10,0) DEFAULT NULL,
  "feedback_timeout" numeric(10,0) DEFAULT NULL,
  "worker_time" numeric(10,0) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "attempts_tag_user_scores" (
  "attempt_id" integer DEFAULT NULL,
  "tag_user_score_id" integer DEFAULT NULL
);

CREATE TABLE "choices" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "multiple_choice_prompt_id" integer NOT NULL,
  "position" integer NOT NULL,
  "feedback" text DEFAULT NULL,
  "value" double precision NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "answer" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "choices_multiple_choice_prompt_answers" (
  "choice_id" integer DEFAULT NULL,
  "multiple_choice_prompt_answer_id" integer DEFAULT NULL
);

CREATE TABLE "coding_prompt_answers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "answer" text DEFAULT NULL,
  "error" text DEFAULT NULL,
  "error_line_no" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "coding_prompts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "class_name" varchar(255) DEFAULT NULL,
  "wrapper_code" text NOT NULL,
  "test_script" text NOT NULL,
  "method_name" varchar(255) DEFAULT NULL,
  "starter_code" text DEFAULT NULL,
  "hide_examples" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "course" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "number" varchar(255) NOT NULL,
  "organization_id" integer NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "creator_id" integer DEFAULT NULL,
  "slug" varchar(255) NOT NULL,
  "user_group_id" integer DEFAULT NULL,
  "is_hidden" boolean DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "course_enrollment" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "course_offering_id" integer NOT NULL,
  "course_role_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "course_exercises" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "course_id" integer NOT NULL,
  "exercise_id" integer NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "course_role" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "can_manage_course" boolean NOT NULL DEFAULT false,
  "can_manage_assignments" boolean NOT NULL DEFAULT false,
  "can_grade_submissions" boolean NOT NULL DEFAULT false,
  "can_view_other_submissions" boolean NOT NULL DEFAULT false,
  "builtin" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "enqueued_job" (
  "discarded" boolean NOT NULL,
  "id" integer NOT NULL,
  "suspended" boolean NOT NULL,
  "queue_time" timestamp DEFAULT NULL,
  "submission_id" integer NOT NULL,
  "worker_id" integer DEFAULT NULL,
  "priority" smallint DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "error" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "usable_type" varchar(255) DEFAULT NULL,
  "usable_id" integer DEFAULT NULL,
  "class_name" varchar(255) DEFAULT NULL,
  "message" text DEFAULT NULL,
  "trace" text DEFAULT NULL,
  "target_url" text DEFAULT NULL,
  "referer_url" text DEFAULT NULL,
  "params" text DEFAULT NULL,
  "user_agent" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercise_collections" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "user_group_id" integer DEFAULT NULL,
  "license_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "user_id" integer DEFAULT NULL,
  "course_offering_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercise_families" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercise_owners" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "exercise_id" integer NOT NULL,
  "owner_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercise_versions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "stem_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "exercise_id" integer NOT NULL,
  "version" integer NOT NULL,
  "creator_id" integer DEFAULT NULL,
  "irt_data_id" integer DEFAULT NULL,
  "text_representation" text DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercise_versions_resource_files" (
  "exercise_version_id" integer NOT NULL,
  "resource_file_id" integer NOT NULL
);

CREATE TABLE "exercise_workouts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "exercise_id" integer NOT NULL,
  "workout_id" integer NOT NULL,
  "position" integer NOT NULL,
  "points" double precision DEFAULT 1,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "exercises" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "question_type" integer NOT NULL,
  "current_version_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "versions" integer DEFAULT NULL,
  "exercise_family_id" integer DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "is_public" boolean NOT NULL DEFAULT false,
  "experience" integer NOT NULL,
  "irt_data_id" integer DEFAULT NULL,
  "external_id" varchar(255) DEFAULT NULL,
  "exercise_collection_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "friendly_id_slugs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "slug" varchar(255) NOT NULL,
  "sluggable_id" integer NOT NULL,
  "sluggable_type" varchar(50) DEFAULT NULL,
  "scope" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "global_role" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "can_manage_all_courses" boolean NOT NULL DEFAULT false,
  "can_edit_system_configuration" boolean NOT NULL DEFAULT false,
  "builtin" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "grading_plugin" (
  "user_id" integer DEFAULT NULL,
  "config_description" bytea DEFAULT NULL,
  "default_config_settings" bytea DEFAULT NULL,
  "id" integer NOT NULL,
  "is_config_file" boolean NOT NULL,
  "is_published" boolean NOT NULL,
  "language_id" integer DEFAULT NULL,
  "main_file_name" text DEFAULT NULL,
  "name" text DEFAULT NULL,
  "subdir_name" text DEFAULT NULL,
  "uploaded_file_name" text DEFAULT NULL,
  "global_config_settings" bytea DEFAULT NULL,
  "file_config_settings" bytea DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "group_access_requests" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer DEFAULT NULL,
  "user_group_id" integer DEFAULT NULL,
  "pending" boolean DEFAULT true,
  "decision" boolean DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "identity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "provider" varchar(255) NOT NULL,
  "uid" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "irt_data" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attempt_count" integer NOT NULL,
  "sum_of_scores" double precision NOT NULL,
  "difficulty" double precision NOT NULL,
  "discrimination" double precision NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "license_policies" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "can_fork" boolean DEFAULT NULL,
  "is_public" boolean DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "licenses" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "url" varchar(255) DEFAULT NULL,
  "license_policy_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "lis_result_id" (
  "id" integer NOT NULL,
  "lis_result_sourcedid" varchar(255) NOT NULL,
  "lms_instance_id" integer NOT NULL,
  "assignment_offering_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "lis_result_source_did" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "lms_instance" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consumer_key" varchar(255) DEFAULT NULL,
  "consumer_secret" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "url" varchar(255) DEFAULT NULL,
  "lms_type_id" integer NOT NULL,
  "organization_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "lms_type" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "lti_identity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lti_user_id" varchar(255) DEFAULT NULL,
  "user_id" integer NOT NULL,
  "lms_instance_id" integer NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "lti_workouts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workout_id" integer DEFAULT NULL,
  "lms_assignment_id" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "lms_instance_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "memberships" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer DEFAULT NULL,
  "user_group_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "multiple_choice_prompt_answers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "multiple_choice_prompts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "allow_multiple" boolean NOT NULL DEFAULT false,
  "is_scrambled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id")
);

CREATE TABLE "organization" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "abbreviation" varchar(255) DEFAULT NULL,
  "slug" varchar(255) NOT NULL,
  "is_hidden" boolean DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "ownerships" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "filename" varchar(255) DEFAULT NULL,
  "resource_file_id" integer DEFAULT NULL,
  "exercise_version_id" integer DEFAULT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "prompt_answers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "attempt_id" integer DEFAULT NULL,
  "prompt_id" integer DEFAULT NULL,
  "actable_id" integer DEFAULT NULL,
  "actable_type" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "prompts" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "exercise_version_id" integer NOT NULL,
  "question" text NOT NULL,
  "position" integer NOT NULL,
  "feedback" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "actable_id" integer DEFAULT NULL,
  "actable_type" varchar(255) DEFAULT NULL,
  "irt_data_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "resource_files" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "filename" varchar(255) DEFAULT NULL,
  "token" varchar(255) NOT NULL,
  "user_id" integer NOT NULL,
  "public" boolean DEFAULT true,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "hashval" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "schema_migrations" (
  "version" varchar(255) NOT NULL
);

CREATE TABLE "section" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "course_id" integer NOT NULL,
  "term_id" integer NOT NULL,
  "label" varchar(255) NOT NULL,
  "url" varchar(255) DEFAULT NULL,
  "self_enrollment_allowed" boolean DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "cutoff_date" date DEFAULT NULL,
  "lms_instance_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "signups" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "first_name" varchar(255) DEFAULT NULL,
  "last_name_name" varchar(255) DEFAULT NULL,
  "email" varchar(255) DEFAULT NULL,
  "institution" varchar(255) DEFAULT NULL,
  "comments" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "stems" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "preamble" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "step" (
  "id" integer NOT NULL,
  "assignment_id" integer DEFAULT NULL,
  "config_settings" bytea DEFAULT NULL,
  "order" integer DEFAULT NULL,
  "grading_plugin_id" integer NOT NULL,
  "step_config_id" integer DEFAULT NULL,
  "timeout" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "step_config" (
  "config_settings" bytea DEFAULT NULL,
  "id" integer NOT NULL,
  "user_id" integer DEFAULT NULL,
  "name" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "student_extensions" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer DEFAULT NULL,
  "workout_offering_id" integer DEFAULT NULL,
  "soft_deadline" timestamp DEFAULT NULL,
  "hard_deadline" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "time_limit" integer DEFAULT NULL,
  "opening_date" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "submission" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workout_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "score" double precision DEFAULT NULL,
  "assignment_offering_id" integer DEFAULT NULL,
  "feedback_ready" boolean NOT NULL DEFAULT false,
  "submit_time" timestamp DEFAULT NULL,
  "last_attempted_at" timestamp DEFAULT NULL,
  "exercises_completed" integer DEFAULT NULL,
  "exercises_remaining" integer DEFAULT NULL,
  "submit_number" integer,
  "lis_result_sourcedid" varchar(255) DEFAULT NULL,
  "submission_result_id" double precision NOT NULL,
  "is_submission_for_grading" boolean NOT NULL DEFAULT false,
  "partner_link" boolean NOT NULL DEFAULT false,
  "primary_submission_id" integer,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "lis_outcome_service_url" varchar(255) DEFAULT NULL,
  "lti_workout_id" integer DEFAULT NULL,
  "started_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "submission_policy" (
  "available_points" double precision DEFAULT NULL,
  "available_time_delta" bigint DEFAULT NULL,
  "award_early_bonus" boolean NOT NULL,
  "dead_time_delta" bigint DEFAULT NULL,
  "deduct_late_penalty" boolean NOT NULL,
  "early_bonus_max_pts" double precision DEFAULT NULL,
  "early_bonus_unit_pts" double precision DEFAULT NULL,
  "early_bonus_unit_time" bigint DEFAULT NULL,
  "id" integer NOT NULL,
  "late_penalty_max_pts" double precision DEFAULT NULL,
  "late_penalty_unit_pts" double precision DEFAULT NULL,
  "late_penalty_unit_time" bigint DEFAULT NULL,
  "max_file_upload_size" bigint DEFAULT NULL,
  "max_submits" integer DEFAULT NULL,
  "name" text DEFAULT NULL,
  "score_format" text DEFAULT NULL,
  "ta_points" double precision DEFAULT NULL,
  "tool_points" double precision DEFAULT NULL,
  "user_id" integer DEFAULT NULL,
  "included_file_patterns" text DEFAULT NULL,
  "excluded_file_patterns" text DEFAULT NULL,
  "required_file_patterns" text DEFAULT NULL,
  "submisison_method" smallint NOT NULL DEFAULT 0,
  "allow_partners" boolean NOT NULL,
  "deduct_excess_submission_penalty" boolean NOT NULL DEFAULT false,
  "excess_submissions_max_pts" double precision DEFAULT NULL,
  "excess_submissions_threshold" integer DEFAULT NULL,
  "excess_submissions_unit_pts" double precision DEFAULT NULL,
  "excess_submissions_unit_size" integer DEFAULT NULL,
  "auto_assign_partners" boolean NOT NULL DEFAULT true,
  "energy_bar_config_id" integer DEFAULT NULL,
  "force_lti_clickthrough" boolean NOT NULL,
  "use_time_bank_days" boolean NOT NULL,
  "time_bank_name" text DEFAULT NULL,
  "time_bank_size" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "submission_result" (
  "correctness_score" double precision NOT NULL,
  "tool_score" double precision,
  "ta_score" double precision,
  "comments" text,
  "comment_format" smallint,
  "last_updated" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("correctness_score")
);

CREATE TABLE "tag_user_scores" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer NOT NULL,
  "experience" integer DEFAULT 0,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "completed_exercises" integer DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE "taggings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tag_id" integer DEFAULT NULL,
  "taggable_id" integer DEFAULT NULL,
  "taggable_type" varchar(255) DEFAULT NULL,
  "tagger_id" integer DEFAULT NULL,
  "tagger_type" varchar(255) DEFAULT NULL,
  "context" varchar(128) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "tags" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "taggings_count" integer DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE TABLE "term" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "season" integer NOT NULL,
  "starts_on" date NOT NULL,
  "ends_on" date NOT NULL,
  "year" integer NOT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "slug" varchar(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "test_case_results" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "test_case_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "execution_feedback" text DEFAULT NULL,
  "feedback_line_no" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "pass" boolean NOT NULL,
  "coding_prompt_answer_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "test_cases" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "negative_feedback" text DEFAULT NULL,
  "weight" double precision NOT NULL,
  "description" text DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "coding_prompt_id" integer NOT NULL,
  "input" text NOT NULL,
  "expected_output" text NOT NULL,
  "static" boolean NOT NULL DEFAULT false,
  "screening" boolean NOT NULL DEFAULT false,
  "example" boolean NOT NULL DEFAULT false,
  "hidden" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);

CREATE TABLE "time_zones" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "zone" varchar(255) DEFAULT NULL,
  "display_as" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(255) NOT NULL,
  "encrypted_password" varchar(255) NOT NULL,
  "reset_password_token" varchar(255) DEFAULT NULL,
  "reset_password_sent_at" timestamp DEFAULT NULL,
  "remember_created_at" timestamp DEFAULT NULL,
  "sign_in_count" integer NOT NULL DEFAULT 0,
  "current_sign_in_at" timestamp DEFAULT NULL,
  "last_sign_in_at" timestamp DEFAULT NULL,
  "current_sign_in_ip" varchar(255) DEFAULT NULL,
  "last_sign_in_ip" varchar(255) DEFAULT NULL,
  "confirmation_token" varchar(255) DEFAULT NULL,
  "confirmed_at" timestamp DEFAULT NULL,
  "confirmation_sent_at" timestamp DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "first_name" varchar(255) DEFAULT NULL,
  "last_name" varchar(255) DEFAULT NULL,
  "global_role_id" integer NOT NULL,
  "avatar" varchar(255) DEFAULT NULL,
  "slug" varchar(255) NOT NULL,
  "current_workout_score_id" integer DEFAULT NULL,
  "time_zone_id" integer DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "user_groups" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "description" text DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "visualization_loggings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer DEFAULT NULL,
  "exercise_id" integer DEFAULT NULL,
  "workout_id" integer DEFAULT NULL,
  "workout_offering_id" integer DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "workout_owners" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workout_id" integer NOT NULL,
  "owner_id" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "workout_policies" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "hide_thumbnails_before_start" boolean DEFAULT NULL,
  "hide_feedback_before_finish" boolean DEFAULT NULL,
  "hide_compilation_feedback_before_finish" boolean DEFAULT NULL,
  "no_review_before_close" boolean DEFAULT NULL,
  "hide_feedback_in_review_before_close" boolean DEFAULT NULL,
  "hide_thumbnails_in_review_before_close" boolean DEFAULT NULL,
  "no_hints" boolean DEFAULT NULL,
  "no_faq" boolean DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "created_at" timestamp DEFAULT NULL,
  "updated_at" timestamp DEFAULT NULL,
  "invisible_before_review" boolean DEFAULT NULL,
  "description" varchar(255) DEFAULT NULL,
  "hide_score_before_finish" boolean DEFAULT NULL,
  "hide_score_in_review_before_close" boolean DEFAULT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "index_active_admin_comments_on_author_type_and_author_id" ON "active_admin_comments" ("author_type" ASC, "author_id" ASC);

CREATE INDEX "index_active_admin_comments_on_namespace" ON "active_admin_comments" ("namespace" ASC);

CREATE INDEX "index_active_admin_comments_on_resource_type_and_resource_id" ON "active_admin_comments" ("resource_type" ASC, "resource_id" ASC);

CREATE INDEX "index_workouts_on_is_public" ON "assignment" ("is_public" ASC);

CREATE INDEX "workouts_creator_id_fk" ON "assignment" ("user_id" ASC);

CREATE INDEX "index_workout_offerings_on_course_offering_id" ON "assignment_offering" ("course_offering_id" ASC);

CREATE INDEX "index_workout_offerings_on_lms_assignment_id" ON "assignment_offering" ("lms_assignment_id" ASC);

CREATE INDEX "index_workout_offerings_on_workout_id" ON "assignment_offering" ("assignment_id" ASC);

CREATE INDEX "index_workout_offerings_on_workout_policy_id" ON "assignment_offering" ("workout_policy_id" ASC);

CREATE INDEX "workout_offerings_continue_from_workout_id_fk" ON "assignment_offering" ("continue_from_workout_id" ASC);

CREATE INDEX "idx_attempts_on_user_exercise_version" ON "attempts" ("user_id" ASC, "exercise_version_id" ASC);

CREATE INDEX "idx_attempts_on_workout_score_exercise_version" ON "attempts" ("workout_score_id" ASC, "exercise_version_id" ASC);

CREATE INDEX "index_attempts_on_active_score_id" ON "attempts" ("active_score_id" ASC);

CREATE INDEX "index_attempts_on_exercise_version_id" ON "attempts" ("exercise_version_id" ASC);

CREATE INDEX "index_attempts_on_user_id" ON "attempts" ("user_id" ASC);

CREATE INDEX "index_attempts_on_workout_score_id" ON "attempts" ("workout_score_id" ASC);

CREATE INDEX "attempts_tag_user_scores_tag_user_score_id_fk" ON "attempts_tag_user_scores" ("tag_user_score_id" ASC);

CREATE INDEX "index_choices_on_multiple_choice_prompt_id" ON "choices" ("multiple_choice_prompt_id" ASC);

CREATE INDEX "choices_MC_prompt_answers_MC_prompt_answer_id_fk" ON "choices_multiple_choice_prompt_answers" ("multiple_choice_prompt_answer_id" ASC);

CREATE INDEX "index_courses_on_organization_id" ON "course" ("organization_id" ASC);

CREATE INDEX "index_courses_on_slug" ON "course" ("slug" ASC);

CREATE INDEX "index_courses_on_user_group_id" ON "course" ("user_group_id" ASC);

CREATE INDEX "index_course_enrollments_on_course_offering_id" ON "course_enrollment" ("course_offering_id" ASC);

CREATE INDEX "index_course_enrollments_on_course_role_id" ON "course_enrollment" ("course_role_id" ASC);

CREATE INDEX "index_course_enrollments_on_user_id" ON "course_enrollment" ("user_id" ASC);

CREATE INDEX "course_exercises_course_id_fk" ON "course_exercises" ("course_id" ASC);

CREATE INDEX "course_exercises_exercise_id_fk" ON "course_exercises" ("exercise_id" ASC);

CREATE INDEX "index_errors_on_class_name" ON "error" ("class_name" ASC);

CREATE INDEX "index_errors_on_created_at" ON "error" ("created_at" ASC);

CREATE INDEX "index_exercise_collections_on_course_offering_id" ON "exercise_collections" ("course_offering_id" ASC);

CREATE INDEX "index_exercise_collections_on_license_id" ON "exercise_collections" ("license_id" ASC);

CREATE INDEX "index_exercise_collections_on_user_group_id" ON "exercise_collections" ("user_group_id" ASC);

CREATE INDEX "index_exercise_collections_on_user_id" ON "exercise_collections" ("user_id" ASC);

CREATE INDEX "exercise_owners_owner_id_fk" ON "exercise_owners" ("owner_id" ASC);

CREATE INDEX "exercise_versions_creator_id_fk" ON "exercise_versions" ("creator_id" ASC);

CREATE INDEX "exercise_versions_irt_data_id_fk" ON "exercise_versions" ("irt_data_id" ASC);

CREATE INDEX "index_exercise_versions_on_exercise_id" ON "exercise_versions" ("exercise_id" ASC);

CREATE INDEX "index_exercise_versions_on_stem_id" ON "exercise_versions" ("stem_id" ASC);

CREATE INDEX "index_exercise_versions_resource_files_on_exercise_version_id" ON "exercise_versions_resource_files" ("exercise_version_id" ASC);

CREATE INDEX "index_exercise_versions_resource_files_on_resource_file_id" ON "exercise_versions_resource_files" ("resource_file_id" ASC);

CREATE INDEX "exercise_workouts_exercise_id_fk" ON "exercise_workouts" ("exercise_id" ASC);

CREATE INDEX "exercise_workouts_workout_id_fk" ON "exercise_workouts" ("workout_id" ASC);

CREATE INDEX "exercises_irt_data_id_fk" ON "exercises" ("irt_data_id" ASC);

CREATE INDEX "index_exercises_on_current_version_id" ON "exercises" ("current_version_id" ASC);

CREATE INDEX "index_exercises_on_exercise_collection_id" ON "exercises" ("exercise_collection_id" ASC);

CREATE INDEX "index_exercises_on_exercise_family_id" ON "exercises" ("exercise_family_id" ASC);

CREATE INDEX "index_exercises_on_is_public" ON "exercises" ("is_public" ASC);

CREATE INDEX "index_friendly_id_slugs_on_slug_and_sluggable_type" ON "friendly_id_slugs" ("slug" ASC, "sluggable_type" ASC);

CREATE INDEX "index_friendly_id_slugs_on_sluggable_id" ON "friendly_id_slugs" ("sluggable_id" ASC);

CREATE INDEX "index_friendly_id_slugs_on_sluggable_type" ON "friendly_id_slugs" ("sluggable_type" ASC);

CREATE INDEX "user_id" ON "grading_plugin" ("user_id" ASC);

CREATE INDEX "index_group_access_requests_on_user_group_id" ON "group_access_requests" ("user_group_id" ASC);

CREATE INDEX "index_group_access_requests_on_user_id" ON "group_access_requests" ("user_id" ASC);

CREATE INDEX "index_identities_on_uid_and_provider" ON "identity" ("uid" ASC, "provider" ASC);

CREATE INDEX "index_identities_on_user_id" ON "identity" ("user_id" ASC);

CREATE INDEX "index_licenses_on_license_policy_id" ON "licenses" ("license_policy_id" ASC);

CREATE INDEX "index_lms_instances_on_organization_id" ON "lms_instance" ("organization_id" ASC);

CREATE INDEX "lms_instances_lms_type_id_fk" ON "lms_instance" ("lms_type_id" ASC);

CREATE INDEX "index_lti_identities_on_lms_instance_id" ON "lti_identity" ("lms_instance_id" ASC);

CREATE INDEX "index_lti_identities_on_lti_user_id" ON "lti_identity" ("lti_user_id" ASC);

CREATE INDEX "index_lti_identities_on_user_id" ON "lti_identity" ("user_id" ASC);

CREATE INDEX "index_lti_workouts_on_lms_instance_id" ON "lti_workouts" ("lms_instance_id" ASC);

CREATE INDEX "index_lti_workouts_on_workout_id" ON "lti_workouts" ("workout_id" ASC);

CREATE INDEX "index_ownerships_on_exercise_version_id" ON "ownerships" ("exercise_version_id" ASC);

CREATE INDEX "index_ownerships_on_filename" ON "ownerships" ("filename" ASC);

CREATE INDEX "index_ownerships_on_resource_file_id" ON "ownerships" ("resource_file_id" ASC);

CREATE INDEX "index_prompt_answers_on_actable_id" ON "prompt_answers" ("actable_id" ASC);

CREATE INDEX "index_prompt_answers_on_attempt_id" ON "prompt_answers" ("attempt_id" ASC);

CREATE INDEX "index_prompt_answers_on_prompt_id" ON "prompt_answers" ("prompt_id" ASC);

CREATE INDEX "index_prompts_on_actable_id" ON "prompts" ("actable_id" ASC);

CREATE INDEX "index_prompts_on_exercise_version_id" ON "prompts" ("exercise_version_id" ASC);

CREATE INDEX "prompts_irt_data_id_fk" ON "prompts" ("irt_data_id" ASC);

CREATE INDEX "index_resource_files_on_hashval" ON "resource_files" ("hashval" ASC);

CREATE INDEX "index_resource_files_on_token" ON "resource_files" ("token" ASC);

CREATE INDEX "index_resource_files_on_user_id" ON "resource_files" ("user_id" ASC);

CREATE INDEX "index_course_offerings_on_course_id" ON "section" ("course_id" ASC);

CREATE INDEX "index_course_offerings_on_lms_instance_id" ON "section" ("lms_instance_id" ASC);

CREATE INDEX "index_course_offerings_on_term_id" ON "section" ("term_id" ASC);

CREATE INDEX "assignment_id" ON "step" ("assignment_id" ASC);

CREATE INDEX "grading_plugin_id" ON "step" ("grading_plugin_id" ASC);

CREATE INDEX "step_config_id" ON "step" ("step_config_id" ASC);

CREATE INDEX "user_id" ON "step_config" ("user_id" ASC);

CREATE INDEX "index_student_extensions_on_user_id" ON "student_extensions" ("user_id" ASC);

CREATE INDEX "index_student_extensions_on_workout_offering_id" ON "student_extensions" ("workout_offering_id" ASC);

CREATE INDEX "idx_ws_on_user_workout_workout_offering" ON "submission" ("user_id" ASC, "workout_id" ASC, "assignment_offering_id" ASC);

CREATE INDEX "index_workout_scores_on_lti_workout_id" ON "submission" ("lti_workout_id" ASC);

CREATE INDEX "index_workout_scores_on_user_id" ON "submission" ("user_id" ASC);

CREATE INDEX "index_workout_scores_on_workout_id" ON "submission" ("workout_id" ASC);

CREATE INDEX "workout_scores_workout_offering_id_fk" ON "submission" ("assignment_offering_id" ASC);

CREATE INDEX "user_id" ON "submission_policy" ("user_id" ASC);

CREATE INDEX "index_tag_user_scores_on_user_id" ON "tag_user_scores" ("user_id" ASC);

CREATE INDEX "index_taggings_on_context" ON "taggings" ("context" ASC);

CREATE INDEX "index_taggings_on_tag_id" ON "taggings" ("tag_id" ASC);

CREATE INDEX "index_taggings_on_taggable_id" ON "taggings" ("taggable_id" ASC);

CREATE INDEX "index_taggings_on_taggable_id_and_taggable_type_and_context" ON "taggings" ("taggable_id" ASC, "taggable_type" ASC, "context" ASC);

CREATE INDEX "index_taggings_on_taggable_type" ON "taggings" ("taggable_type" ASC);

CREATE INDEX "index_taggings_on_tagger_id" ON "taggings" ("tagger_id" ASC);

CREATE INDEX "index_taggings_on_tagger_id_and_tagger_type" ON "taggings" ("tagger_id" ASC, "tagger_type" ASC);

CREATE INDEX "taggings_idy" ON "taggings" ("taggable_id" ASC, "taggable_type" ASC, "tagger_id" ASC, "context" ASC);

CREATE INDEX "index_terms_on_year_and_season" ON "term" ("year" ASC, "season" ASC);

CREATE INDEX "index_test_case_results_on_coding_prompt_answer_id" ON "test_case_results" ("coding_prompt_answer_id" ASC);

CREATE INDEX "index_test_case_results_on_test_case_id" ON "test_case_results" ("test_case_id" ASC);

CREATE INDEX "index_test_case_results_on_user_id" ON "test_case_results" ("user_id" ASC);

CREATE INDEX "index_test_cases_on_coding_prompt_id" ON "test_cases" ("coding_prompt_id" ASC);

CREATE INDEX "index_users_on_global_role_id" ON "user" ("global_role_id" ASC);

CREATE INDEX "index_users_on_time_zone_id" ON "user" ("time_zone_id" ASC);

CREATE INDEX "index_visualization_loggings_on_exercise_id" ON "visualization_loggings" ("exercise_id" ASC);

CREATE INDEX "index_visualization_loggings_on_user_id" ON "visualization_loggings" ("user_id" ASC);

CREATE INDEX "index_visualization_loggings_on_workout_id" ON "visualization_loggings" ("workout_id" ASC);

CREATE INDEX "index_visualization_loggings_on_workout_offering_id" ON "visualization_loggings" ("workout_offering_id" ASC);

CREATE INDEX "workout_owners_owner_id_fk" ON "workout_owners" ("owner_id" ASC);

ALTER TABLE "assignment" ADD CONSTRAINT "fk_assignment_1" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "assignment" ADD CONSTRAINT "fk_assignment_2" FOREIGN KEY ("submission_policy_id") REFERENCES "submission_policy" ("id");

ALTER TABLE "assignment_offering" ADD CONSTRAINT "fk_assignment_offering_3" FOREIGN KEY ("workout_policy_id") REFERENCES "workout_policies" ("id");

ALTER TABLE "assignment_offering" ADD CONSTRAINT "fk_assignment_offering_4" FOREIGN KEY ("assignment_id") REFERENCES "assignment" ("id");

ALTER TABLE "assignment_offering" ADD CONSTRAINT "fk_assignment_offering_5" FOREIGN KEY ("continue_from_workout_id") REFERENCES "assignment_offering" ("id");

ALTER TABLE "assignment_offering" ADD CONSTRAINT "fk_assignment_offering_6" FOREIGN KEY ("course_offering_id") REFERENCES "section" ("id");

ALTER TABLE "attempts" ADD CONSTRAINT "fk_attempts_7" FOREIGN KEY ("active_score_id") REFERENCES "submission" ("id");

ALTER TABLE "attempts" ADD CONSTRAINT "fk_attempts_8" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "attempts" ADD CONSTRAINT "fk_attempts_9" FOREIGN KEY ("workout_score_id") REFERENCES "submission" ("id");

ALTER TABLE "attempts" ADD CONSTRAINT "fk_attempts_10" FOREIGN KEY ("exercise_version_id") REFERENCES "exercise_versions" ("id");

ALTER TABLE "attempts_tag_user_scores" ADD CONSTRAINT "fk_attempts_tag_user_scores_11" FOREIGN KEY ("tag_user_score_id") REFERENCES "tag_user_scores" ("id");

ALTER TABLE "attempts_tag_user_scores" ADD CONSTRAINT "fk_attempts_tag_user_scores_12" FOREIGN KEY ("attempt_id") REFERENCES "attempts" ("id");

ALTER TABLE "choices" ADD CONSTRAINT "fk_choices_13" FOREIGN KEY ("multiple_choice_prompt_id") REFERENCES "multiple_choice_prompts" ("id");

ALTER TABLE "choices_multiple_choice_prompt_answers" ADD CONSTRAINT "fk_choices_multiple_choice_prompt_answers_14" FOREIGN KEY ("choice_id") REFERENCES "choices" ("id");

ALTER TABLE "choices_multiple_choice_prompt_answers" ADD CONSTRAINT "fk_choices_multiple_choice_prompt_answers_15" FOREIGN KEY ("multiple_choice_prompt_answer_id") REFERENCES "multiple_choice_prompt_answers" ("id");

ALTER TABLE "course" ADD CONSTRAINT "fk_course_16" FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "course_enrollment" ADD CONSTRAINT "fk_course_enrollment_17" FOREIGN KEY ("course_role_id") REFERENCES "course_role" ("id");

ALTER TABLE "course_enrollment" ADD CONSTRAINT "fk_course_enrollment_18" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "course_enrollment" ADD CONSTRAINT "fk_course_enrollment_19" FOREIGN KEY ("course_offering_id") REFERENCES "section" ("id");

ALTER TABLE "course_exercises" ADD CONSTRAINT "fk_course_exercises_20" FOREIGN KEY ("course_id") REFERENCES "course" ("id");

ALTER TABLE "course_exercises" ADD CONSTRAINT "fk_course_exercises_21" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "enqueued_job" ADD CONSTRAINT "fk_enqueued_job_22" FOREIGN KEY ("submission_id") REFERENCES "submission" ("id");

ALTER TABLE "exercise_owners" ADD CONSTRAINT "fk_exercise_owners_23" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_owners" ADD CONSTRAINT "fk_exercise_owners_24" FOREIGN KEY ("owner_id") REFERENCES "user" ("id");

ALTER TABLE "exercise_versions" ADD CONSTRAINT "fk_exercise_versions_25" FOREIGN KEY ("creator_id") REFERENCES "user" ("id");

ALTER TABLE "exercise_versions" ADD CONSTRAINT "fk_exercise_versions_26" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_versions" ADD CONSTRAINT "fk_exercise_versions_27" FOREIGN KEY ("stem_id") REFERENCES "stems" ("id");

ALTER TABLE "exercise_versions" ADD CONSTRAINT "fk_exercise_versions_28" FOREIGN KEY ("irt_data_id") REFERENCES "irt_data" ("id");

ALTER TABLE "exercise_versions_resource_files" ADD CONSTRAINT "fk_exercise_versions_resource_files_29" FOREIGN KEY ("resource_file_id") REFERENCES "resource_files" ("id");

ALTER TABLE "exercise_versions_resource_files" ADD CONSTRAINT "fk_exercise_versions_resource_files_30" FOREIGN KEY ("exercise_version_id") REFERENCES "exercise_versions" ("id");

ALTER TABLE "exercise_workouts" ADD CONSTRAINT "fk_exercise_workouts_31" FOREIGN KEY ("exercise_id") REFERENCES "exercises" ("id");

ALTER TABLE "exercise_workouts" ADD CONSTRAINT "fk_exercise_workouts_32" FOREIGN KEY ("workout_id") REFERENCES "assignment" ("id");

ALTER TABLE "exercises" ADD CONSTRAINT "fk_exercises_33" FOREIGN KEY ("irt_data_id") REFERENCES "irt_data" ("id");

ALTER TABLE "exercises" ADD CONSTRAINT "fk_exercises_34" FOREIGN KEY ("exercise_family_id") REFERENCES "exercise_families" ("id");

ALTER TABLE "exercises" ADD CONSTRAINT "fk_exercises_35" FOREIGN KEY ("current_version_id") REFERENCES "exercise_versions" ("id");

ALTER TABLE "identity" ADD CONSTRAINT "fk_identity_36" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "lis_result_id" ADD CONSTRAINT "fk_lis_result_id_37" FOREIGN KEY ("assignment_offering_id") REFERENCES "assignment_offering" ("id");

ALTER TABLE "lis_result_id" ADD CONSTRAINT "fk_lis_result_id_38" FOREIGN KEY ("lms_instance_id") REFERENCES "lms_instance" ("id");

ALTER TABLE "lis_result_id" ADD CONSTRAINT "fk_lis_result_id_39" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "lms_instance" ADD CONSTRAINT "fk_lms_instance_40" FOREIGN KEY ("lms_type_id") REFERENCES "lms_type" ("id");

ALTER TABLE "lms_instance" ADD CONSTRAINT "fk_lms_instance_41" FOREIGN KEY ("organization_id") REFERENCES "organization" ("id");

ALTER TABLE "lms_instance" ADD CONSTRAINT "fk_lms_instance_42" FOREIGN KEY ("id") REFERENCES "organization" ("id");

ALTER TABLE "lti_identity" ADD CONSTRAINT "fk_lti_identity_43" FOREIGN KEY ("lms_instance_id") REFERENCES "lms_instance" ("id");

ALTER TABLE "lti_identity" ADD CONSTRAINT "fk_lti_identity_44" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "lti_workouts" ADD CONSTRAINT "fk_lti_workouts_45" FOREIGN KEY ("lms_instance_id") REFERENCES "lms_instance" ("id");

ALTER TABLE "organization" ADD CONSTRAINT "fk_organization_46" FOREIGN KEY ("id") REFERENCES "lms_instance" ("id");

ALTER TABLE "ownerships" ADD CONSTRAINT "fk_ownerships_47" FOREIGN KEY ("exercise_version_id") REFERENCES "exercise_versions" ("id");

ALTER TABLE "ownerships" ADD CONSTRAINT "fk_ownerships_48" FOREIGN KEY ("resource_file_id") REFERENCES "resource_files" ("id");

ALTER TABLE "prompt_answers" ADD CONSTRAINT "fk_prompt_answers_49" FOREIGN KEY ("attempt_id") REFERENCES "attempts" ("id");

ALTER TABLE "prompt_answers" ADD CONSTRAINT "fk_prompt_answers_50" FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id");

ALTER TABLE "prompts" ADD CONSTRAINT "fk_prompts_51" FOREIGN KEY ("irt_data_id") REFERENCES "irt_data" ("id");

ALTER TABLE "prompts" ADD CONSTRAINT "fk_prompts_52" FOREIGN KEY ("exercise_version_id") REFERENCES "exercise_versions" ("id");

ALTER TABLE "resource_files" ADD CONSTRAINT "fk_resource_files_53" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "section" ADD CONSTRAINT "fk_section_54" FOREIGN KEY ("course_id") REFERENCES "course" ("id");

ALTER TABLE "section" ADD CONSTRAINT "fk_section_55" FOREIGN KEY ("term_id") REFERENCES "term" ("id");

ALTER TABLE "step" ADD CONSTRAINT "fk_step_56" FOREIGN KEY ("assignment_id") REFERENCES "assignment" ("id");

ALTER TABLE "step" ADD CONSTRAINT "fk_step_57" FOREIGN KEY ("id") REFERENCES "step_config" ("id");

ALTER TABLE "step" ADD CONSTRAINT "fk_step_58" FOREIGN KEY ("grading_plugin_id") REFERENCES "grading_plugin" ("id");

ALTER TABLE "step" ADD CONSTRAINT "fk_step_59" FOREIGN KEY ("step_config_id") REFERENCES "step_config" ("id");

ALTER TABLE "student_extensions" ADD CONSTRAINT "fk_student_extensions_60" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "student_extensions" ADD CONSTRAINT "fk_student_extensions_61" FOREIGN KEY ("workout_offering_id") REFERENCES "assignment_offering" ("id");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_62" FOREIGN KEY ("assignment_offering_id") REFERENCES "assignment_offering" ("id");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_63" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_64" FOREIGN KEY ("lti_workout_id") REFERENCES "lti_workouts" ("id");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_65" FOREIGN KEY ("workout_id") REFERENCES "assignment" ("id");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_66" FOREIGN KEY ("submission_result_id") REFERENCES "submission_result" ("correctness_score");

ALTER TABLE "submission" ADD CONSTRAINT "fk_submission_67" FOREIGN KEY ("primary_submission_id") REFERENCES "submission" ("id");

ALTER TABLE "tag_user_scores" ADD CONSTRAINT "fk_tag_user_scores_68" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "test_case_results" ADD CONSTRAINT "fk_test_case_results_69" FOREIGN KEY ("test_case_id") REFERENCES "test_cases" ("id");

ALTER TABLE "test_case_results" ADD CONSTRAINT "fk_test_case_results_70" FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "test_case_results" ADD CONSTRAINT "fk_test_case_results_71" FOREIGN KEY ("coding_prompt_answer_id") REFERENCES "coding_prompt_answers" ("id");

ALTER TABLE "test_cases" ADD CONSTRAINT "fk_test_cases_72" FOREIGN KEY ("coding_prompt_id") REFERENCES "coding_prompts" ("id");

ALTER TABLE "user" ADD CONSTRAINT "fk_user_73" FOREIGN KEY ("time_zone_id") REFERENCES "time_zones" ("id");

ALTER TABLE "user" ADD CONSTRAINT "fk_user_74" FOREIGN KEY ("global_role_id") REFERENCES "global_role" ("id");

ALTER TABLE "user" ADD CONSTRAINT "fk_user_75" FOREIGN KEY ("current_workout_score_id") REFERENCES "submission" ("id");

ALTER TABLE "workout_owners" ADD CONSTRAINT "fk_workout_owners_76" FOREIGN KEY ("owner_id") REFERENCES "user" ("id");
